### PR TITLE
Adapt to new pangolin output

### PR DESCRIPTION
**Pull request by henningonsbring**
Before pangolin gave an .csv as output with the following headers:
`taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note`

Now pangolin will give an .csv output with the following headers:
`taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note`

In a file given as output by MUTANT (`...pangolin_classification_format3.txt`) we have the following headers:
`taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note`

The `...pangolin_classification_format3.txt` is now going to be upgraded to `...pangolin_classification_format4.txt` with the following headers:
`taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note`

From the `...pangolin_classification_formatX.txt` file we collect information regarding `lineage`, `ambiguity_score`,  `pangoLEARN_version` and `qc_status`. While `lineage` and `ambiguity_score` stay in the same column index we need to take into consideration that the `pangoLEARN_version` column gets deprecated and `status` column change place.

I suggest we display `pangolin_version` from now on in the customer reports.

### Preparations:

**How to prepare mutant for test**:
* `cd MUTANT`
* `bash mutant/standalone/deploy_hasta_update.sh stage <MUTANT_branch>`

**How to prepare cg for test**:
- `us`
- Paxa and update cg:
  - `paxa -u <user> -s hasta -r cg-stage`
  - `bash update-cg-stage.sh master`
- If needed, paxa and update servers:
  - `paxa -u <user> -s hasta -r servers-stage`
  - `bash update-servers-stage.sh <master/branch>`
  
### How to test:
Run in a tmux screen or similar if testing on a large dataset.

**Test with cg**:
- `us`
- `cg workflow mutant start maturejay`

### Expected outcome:
- [ ] Produced files contain expected values

### Review:
- [ ] Code reviewed by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henningonsbring** [comment]
PR in cg: https://github.com/Clinical-Genomics/cg/pull/1454

**Comment by henningonsbring** [comment]
@talnor @sofstam what do you think about showing `pangolin_version` instead of `pangoLEARN_version`?

**Comment by talnor** [comment]
> @talnor @sofstam what do you think about showing `pangolin_version` instead of `pangoLEARN_version` in the report to customer?

https://github.com/Clinical-Genomics/MUTANT/issues/137

**Review by talnor — APPROVED** [review]
Looks good!

**Comment by henningonsbring** [comment]
We need this merged first: https://github.com/genomic-medicine-sweden/gms-artic/pull/56

Or in some way deal with the upgraded nextclade that require other input from v1.10.0

**Comment by henningonsbring** [comment]
lets merge this instead: https://github.com/Clinical-Genomics/MUTANT/pull/139

**Pull request closed without merging**
