### PR TITLE
Update gms-artic version

### PR DESCRIPTION
**Pull request by henningonsbring**
### The purpose of the code changes are as follows:
-  Update to latest version of gms-artic

### Preparations:

**How to prepare mutant for test**:
* `cd MUTANT`
* `bash mutant/standalone/deploy_hasta_update.sh stage <MUTANT_branch>`

**How to prepare cg for test**:
- `us`
- Paxa and update cg:
  - `paxa -u <user> -s hasta -r cg-stage`
  - `bash update-cg-stage.sh master`
- If needed, paxa and update servers:
  - `paxa -u <user> -s hasta -r servers-stage`
  - `bash update-servers-stage.sh <master/branch>`
  
### How to test:
Run in a tmux screen or similar if testing on a large dataset.

**Test with cg**:
- `us`
- `cg workflow mutant start maturejay`

### Expected outcome:
- [ ] Produced files contain expected values

### Review:
- [ ] Code reviewed by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henningonsbring** [comment]
@sofstam please review and before merge and deploy on hasta you need to upload new container to gms-dockerhub, right now when running `singularity pull --force /home/proj/stage/mutant/MUTANT/mutant/externals/gms-artic/artic-ncov2019-illumina.sif docker://genomicmedicinesweden/gms-artic-illumina` I get the same R-error:
```
singularity exec /home/proj/stage/mutant/MUTANT/mutant/externals/gms-artic/artic-ncov2019-illumina.sif R
/opt/conda/envs/artic-ncov2019-illumina/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```

**Comment by sofstam** [comment]
@henningonsbring The automatic upload to GMS dockerhub failed and that is why you still get the error. I will manually upload the container and then look into why the automatic upload keeps failing.

**Comment by sofstam** [comment]
@henningonsbring New container uploaded in GMS dockerhub with a working R.

**Comment by henningonsbring** [comment]
Since there is already a new version of gms-artic I will close this PR and make a new one with the latest version

**Pull request closed without merging**
