### PR TITLE
Update sars-cov-2 report

### PR DESCRIPTION
**Pull request by talnor**
### The purpose of the code changes are as follows:
-  Add code by Isak to update the sars-cov-2 report.
   - column "variants" changed to "mutations"
   - column "VOC" will show values for all classes (including VOC, VOI, VUM etc) as defined in `mutant/standalone/classifications.csv`
   - new column for region codes
   
- Also added chmod of singularity image in deploy

### Preparations:

**How to prepare mutant for test**:
* `bash mutant/standalone/deploy_hasta_update.sh stage update_report`

**How to prepare cg for test**:
- `us`
- Paxa and update cg or other tools needed for the test:
  - `paxa -u <user> -s hasta -r cg-stage`
  - `paxa -u <user> -s hasta -r servers-stage`
  - `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh master`
  - `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-servers-stage.sh master`
  

### How to test:
Run in a tmux screen or similar if testing on a large dataset.

**Test with cg**:
- `us`
- `cg workflow mutant start eagereel`

### Expected outcome:
- [x] Produced files contain expected values
- [x] Singularity image has correct permissions

### Review:
- [x] Code reviewed @Mropat 

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by talnor** [comment]
-rwxr-xr-x+ permissions for image

**Comment by Mropat** [comment]
Please wait with merging. Need to check if it interferes with fohm +gisaid upload

**Comment by talnor** [comment]
Output end:
```
Analysis successfully stored in Housekeeper: eagereel : 2021-09-03 13:01:31
Storing analysis in StatusDB for eagereel
Running command source activate S_mutant; /home/proj/bin/conda/envs/S_mutant/bin/mutant --version
Analysis successfully stored in StatusDB: eagereel : 2021-09-03 13:01:31
Action None set for case eagereel
```

**Comment by talnor** [comment]
- Last column renamed to: Mutations
- "VOC" classes in column "VOC"
`Sample,Selection,Region Code,Ticket,%N_bases,%10X_coverage,QC_pass,Lineage,PangoLEARN_version,VOC,Mutations
21CS507020,Allmän övervakning,01,435977,16.64,83.36,FALSE,AY.12,2021-08-24,No,L452R;T478K;D614G
21CS506982,Vaccinationsgenombrott,01,435977,37.02,62.98,FALSE,None,2021-08-24,-,D614G
21CS506984,Vaccinationsgenombrott,01,435977,32.72,67.26,FALSE,None,2021-08-24,-,D614G
21CS507063,Allmän övervakning,01,435977,5.33,94.67,FALSE,AY.9,2021-08-24,No,D614G
21CS507044,Allmän övervakning,01,435977,5.86,94.12,FALSE,AY.9,2021-08-24,No,D614G
21CS507026,Allmän övervakning,01,435977,17.37,82.63,FALSE,AY.12,2021-08-24,No,L452R;Syn.475A;T478K;D614G
21CS507055,Allmän övervakning,01,435977,0.21,99.77,TRUE,B.1.617.2,2021-08-24,VOC,L452R;T478K;D614G`

**Review by Mropat — APPROVED** [review]

**Pull request merged**
