### PR TITLE
Create new file for vogue

### PR DESCRIPTION
**Pull request by talnor**
### The purpose of the code changes are as follows:
- Added new file for vogue input in yaml format

#### Minor changes
- Restructured the modules directory 
- Moved parsing of results to parser.py
- Updated the test-files to the current format of normal input

### Preparations:

**How to prepare mutant for test**:
* `bash mutant/standalone/deploy_hasta_update.sh stage std_vogue_yaml`

**How to prepare cg for test**:
- `us`
- Paxa and update cg or other tools needed for the test:
  - `paxa -u <user> -s hasta -r cg-stage`
  - `bash update-cg-stage.sh master`
  

### How to test:
Run in a tmux screen or similar if testing on a large dataset.

**Test with cg**:
- `us`
- `cg workflow mutant start maturejay`

### Expected outcome:
- [x] Produced files contain expected values

### Review:
- [ ] Code reviewed by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by talnor** [comment]
The vogue input file looks like this (but is named as .yaml)
[tinycase_metrics_deliverables.txt](https://github.com/Clinical-Genomics/MUTANT/files/7475467/tinycase_metrics_deliverables.txt)
s:

**Comment by talnor** [comment]
> The vogue input file looks like this (but is named as .yaml) [tinycase_metrics_deliverables.txt](https://github.com/Clinical-Genomics/MUTANT/files/7475467/tinycase_metrics_deliverables.txt)

In addition: You can find the file from the test on stage at `maturejay/results/maturejay_metrics_deliverables.yaml`

**Comment by talnor** [comment]
Analysis successfully stored in Housekeeper: maturejay : 2021-11-09 12:06:45
Storing analysis in StatusDB for maturejay
Running command source activate S_mutant; /home/proj/bin/conda/envs/S_mutant/bin/mutant --version
Analysis successfully stored in StatusDB: maturejay : 2021-11-09 12:06:45
Action None set for case maturejay

**Review by Mropat — APPROVED** [review]
Great! 🎺🎺

**Comment by henrikstranneheim** [comment]
@talnor well done

**Pull request merged**
